### ISSUE TITLE
Change affine transform

### ISSUE THREAD

**Issue by nden** [spacetelescope/pyasdf#72]
`affine.yaml` requires a 3x3 matrix for the affine transformation. I think the idea was that this may go to higher dimensions in the future. `Pyasdf` splits this into matrix and translation in order to initialize `modeling.AffineTransformation2D` which uses the two quantities separately.

I was assuming pyasdf was writing to disk the augmented matrix but it simply attaches the translation part as an additional row to the matrix. This is confusing.
```
array([[   0.92913257,   -0.36974676,  100.        ],
       [   0.36974676,    0.92913257,   20.        ],
       [   0.        ,    0.        ,    1.        ]])
```
vs
```
matrix: !core/ndarray
    data:
    - [0.92913257, -0.36974676, 0.0]
    - [0.36974676, 0.92913257, 0.0]
    - [100.0, 20.0, 0.0]
    datatype: float64
    shape: [3, 3]
```

In addition,  `modeling.AffineTranslation2D` is the only option currently that can be used to apply the PC matrix in WCS transformations. However I am only able to write a 3x3 matrix as an affine transformation. This is also confusing because it may mean the data is 3 dimensional in the WCS context.

Any ideas how to resolve this? This is also related to astropy.modeling issue #3548 which would solve this problem if accepted.
